### ISSUE TITLE
Format errors causing crash at class construction

### ISSUE THREAD

**Issue by vincentlabatut** [anshooarora/extentreports-csharp#14]
Hi,
Our builds are crashing because of a corrupt HTML report file. 
When initializing ExtentReports, it parses the existing HTML report file, here is the exception :
```
System.NullReferenceException : Object reference not set to an instance of an object.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at RelevantCodes.ExtentReports.Converters.TestConverter.<>c.<HTMLNodeToExtentTest>b__4_5(HtmlNode x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RelevantCodes.ExtentReports.Converters.TestConverter.AssignTestAttributes(IEnumerable`1 CategoriesNode, IEnumerable`1 AuthorsNode, ExtentTest ExtentTest)
   at RelevantCodes.ExtentReports.Converters.TestConverter.HTMLNodeToExtentTest(HtmlNode HtmlTestNode)
   at RelevantCodes.ExtentReports.Converters.TestConverter.<>c__DisplayClass3_0.<Convert>b__2(HtmlNode htmlTestNode)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at RelevantCodes.ExtentReports.Converters.TestConverter.Convert()
   at RelevantCodes.ExtentReports.ExtentReports..ctor(String FilePath, Boolean ReplaceExisting, DisplayOrder Order)
```
I have located the corrupt part in the HTML file :
                                                                                     `<td class='step-details'>System.InvalidOperationException : Element is not clickable at point (1717, 96.60000610351562). Other element would receive the click: <span style="width: 1887px; height: 2227px; line-height: 0; background: rgb(0, 0, 0) none repeat scroll 0% 0%; position: absolute; top: 0px; left: 0px; bottom: 0px; z-index: 99998; opacity: 0.4;" id="arena-overlay"></span>`

When I remove the <span>... </span> block from the file, it works agin.
The <span> also causes the browser not to display properly the report.

I suspect this block to come from our own log entries (IE directly from the selenium exception). Can you confirm it is not added by ExtentReport ?
Your advice would to format any log entry to an HTML friendly format ?
(transform < into &lt;   and transform carriage return into <br /> etc... 
Or use System.Web.HttpUtility.HtmlEncode ?

**Comment by anshooarora** [comment]
For now, you can transform the `<` as `&lt;` and `>` as `&gt;`.  Don't think any other elements would need to be parsed this way.  In v3.0, there will be an inbuilt feature to handle such tags.
