### ISSUE TITLE
Sample ExtentX setup 

### ISSUE THREAD

**Issue by DeshdeepDivakar** [anshooarora/extentreports-csharp#15]
Hi Anshoo,

Thank you for the wonderful work you have done! I am just curious if you could site a short example of setting up ExtentX with MongoDB reporting server.

Cheers,
Deshdeep

**Comment by anshooarora** [comment]
The installation examples are available on the website.  I will add images soon to make it easier.

**Comment by DeshdeepDivakar** [comment]
Thank you, Will look forward for that.

**Comment by DeshdeepDivakar** [comment]
Hi Anshoo, I believe the bit I was missing and the documentation doesn't state it clearly that one have to install the sails npm globally for it to work. Please update the doc.

**Comment by anshooarora** [comment]
Thank you,  all docs are a little outdated and I will add your finding to the list of items to add. 

Cheers.

**Comment by IliaFraedom** [comment]
Hi,
it is not clear how to use ExtentX2.2 with ExtentReport 3

Before it was: 
```
var Report = new ExtentReports("....")
Report.X(url);
```

Now I'm trying :
```
var Reporter = new ExtentXReporter();
var Report = new ExtentReports()
Report.AttachReporter(Reporter)
```

And that is not working, because ExtentXReporter not implemntes  IExtentReporter.

Could you help me with that.

**Comment by anshooarora** [comment]
The 1st alpha only has the HtmlReporter.  ExtentXReporter will be added in the next.  It will be after the next version of ExtentX though as lots of enhancements have been included.

**Comment by IliaFraedom** [comment]
Hi @anshooarora, thanks for your response.
Any approximate dates, now using old versions, but want to update to BDD style?

**Comment by anshooarora** [comment]
BDD style reporting will be supported in ExtentReports and ExtentX, but they will be displayed as regular tests in ExtentX (with toggles, as in ExtentReports).

**Comment by IliaFraedom** [comment]
Thanks @anshooarora

**Comment by amitaks2** [comment]
Hi Anshoo,

 I am unable to connect to mongodb server , while i run sails lift command i get below error error: 

```
D:\EXTENT\extentx>sails lift
info: Starting app...
error: A hook (`orm`) failed to load!
error: Error: Failed to connect to MongoDB.  Are you sure your configured Mongo instance is running?
 Error details:
{ Error: connect ETIMEDOUT 54.80.159.104:61001
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  name: 'MongoError',
  message: 'connect ETIMEDOUT 54.80.159.104:61001' }
    at _createError (D:\EXTENT\extentx\node_modules\sails-mongo\lib\adapter.js:116:23)
    at D:\EXTENT\extentx\node_modules\sails-mongo\lib\adapter.js:119:13
    at D:\EXTENT\extentx\node_modules\sails-mongo\lib\connection.js:25:20
    at D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb\lib\mongo_client.js:276:20
    at D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb\lib\db.js:224:14
    at Server.<anonymous> (D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb\lib\server.js:234:9)
    at Server.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at Pool.<anonymous> (D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb-core\lib\topologies\server.js:269:68)
    at Pool.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Pool.emit (events.js:191:7)
    at Connection.<anonymous> (D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb-core\lib\connection\pool.js:81:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
```
My connection.js->

```
module.exports.connections = {
extent: {
    adapter: 'sails-mongo',
    host: 'localhost', // host where MongoDB is running
    port: 27017, // port where MongoDB is running
 //user: 'admin',
    //password: 'admin',
    database: 'extent'
  },
    mlabMongo:{
  
 adapter:'sails-mongo',
 url: 'mongodb://admin:admin@ds161001.mlab.com:61001/extent',
 schema: 'true',
 
  
  }
};
```
My model.js-- >

```
module.exports.models = {
connection: 'mlabMongo',
migrate: 'alter',
  hookTimeout: 60000
};

My Package.json-->


```
{
  "name": "extentx",
  "private": true,
  "version": "1.0.2",
  "description": "AventStack ExtentX Community Version - Report Server for ExtentReports",
  "keywords": [],
  "dependencies": {
    "bcryptjs": "2.3.0",
    "ejs": "2.3.4",
    "grunt": "1.0.1",
    "grunt-contrib-clean": "1.0.0",
    "grunt-contrib-coffee": "1.0.0",
    "grunt-contrib-concat": "1.0.1",
    "grunt-contrib-copy": "1.0.0",
    "grunt-contrib-cssmin": "1.0.1",
    "grunt-contrib-jst": "1.0.0",
    "grunt-contrib-less": "1.3.0",
    "grunt-contrib-uglify": "1.0.1",
    "grunt-contrib-watch": "1.0.0",
    "grunt-sails-linker": "0.10.1",
    "grunt-sync": "0.5.2",
    "include-all": "0.1.6",
    "lodash": "4.15.0",
    "mongodb": "2.1.19",
    "mv": "2.1.1",
    "node-inspector": "^1.1.1",
    "rc": "1.0.1",
    "sails": "0.12.3",
    "sails-disk": "0.10.9",
    "sails-memory": "^0.10.7",
    "sails-mongo": "0.12.0",
    "waterline": "^0.11.11"
  },
  "scripts": {
    "debug": "node debug app.js",
    "start": "node app.js"
  },
  "main": "app.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/amitaks2/extentx.git"
  },
  "author": "AventStack"
}

```

My mlab Database - >
![mlab_database](https://cloud.githubusercontent.com/assets/2518755/26721937/88f1edf2-47ab-11e7-898f-eda81de44e0a.png)

LOCAL MONGO db - >

![showdb](https://cloud.githubusercontent.com/assets/2518755/26721968/a31d21d8-47ab-11e7-91f5-c97806d6ae66.png)

please help me to get application deploy ?

**Comment by plokeshwar** [comment]
Hi @anshooarora,

Thanks for the awesome reporting server.  A quick question.  Is there a functionality for adding users and restricting views?

Thanks in advance.

-Pravin

**Comment by veeramanikandanvv** [comment]
@anshooarora,
1. I want to set the project name as drop-down menu  , submenu model. Say projects within projects. Is there any way to do that.

2. I want to know what is klovreporter
